### ISSUE TITLE
Connect to dynamodb

### ISSUE THREAD

**Issue by 2or3** [2or3/payment#3]
# Overview
- Can connect to DynamoDB table via driver

# Task
- [x] Execute "drive/dynamodb.ml" vis dune
- [x] Get key from environment vars
- [ ] Retrieve data from dynamodb table
- [ ] Create Signature
